Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  ## DB VM ##
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/centos9s"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.30"
    db01.vm.network "public_network"

    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    
    db01.vm.provision "shell", path: "mysql.sh"
  end
  
  ## memcache setup ##
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/centos9s"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.29"
    mc01.vm.network "public_network"

    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    mc01.vm.provision "shell", path: "memcache.sh"
  end

  ## rabbit mq setup ##

  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "generic/centos9s"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.28"
    rmq01.vm.network "public_network"

    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  config.vm.define "app01" do |app01|
    app01.vm.box = "generic/centos9s"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.27"
    app01.vm.network "public_network"

    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    app01.vm.provision "shell", path: "tomcat.sh"
  end

   config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.26"
    web01.vm.network "public_network"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    web01.vm.provision "shell", path: "nginx.sh"
  end
end
